POST http://localhost:8000/auth/refresh-tokens
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI1LCJlbWFpbCI6ImFsaWZAdG9tLmNvbSIsImlhdCI6MTcyODI4Nzc1MywiZXhwIjoxNzI4MjkxMzUzLCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.hRzWxO32omDDjXS8aQ4QufDhl-5dNuCxBL_r00wYdf0
{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI1LCJpYXQiOjE3MjgyODc3NTMsImV4cCI6MTcyODM3NDE1MywiYXVkIjoibG9jYWxob3N0OjgwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6ODAwMCJ9.OqVNJDhARXZbZwurNTlSPCfEEhCcjU-bZVXoMWXKh-I"

}